### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by msharma-rms** [Nestak2/image-sorter2#2]
Unable to run the code, giving following error
IndexError                                Traceback (most recent call last)
<ipython-input-1-c6c3372a1330> in <module>
    389 # Start the GUI
    390 root = tk.Tk()
--> 391 app = ImageGui(root, labels, paths)
    392 root.mainloop()

<ipython-input-1-c6c3372a1330> in __init__(self, master, labels, paths)
    132         #### added in version 2
    133         # Add sorting label
--> 134         sorting_string = df.sorted_in_folder[self.index].split(os.sep)[-2]
    135         self.sorting_label = tk.Label(frame, text=("in folder: %s" % (sorting_string)), width=15)
    136 

IndexError: list index out of range

**Comment by aman17ashray** [comment]
I have fixed it and created a pull request for the same. 
you can find the correct version on - https://github.com/aman17ashray/image-sorter2
